spring:
  application:
    name: eureka-server-instance
  profiles:
    active: eureka-18763


---
server:
  port: 18761

spring:
  config:
    activate:
      on-profile: eureka-18761

eureka:
  instance:
    #eureka server instance ID
    hostname: eureka-18761
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: true
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      #单机版服务注册中心
      defaultZone: http://eureka-18762:18762/eureka/,http://eureka-18763:18763/eureka/

---
server:
  port: 18762

spring:
  config:
    activate:
      on-profile: eureka-18762

eureka:
  instance:
    #eureka server instance ID
    hostname: eureka-18762
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: true
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      #单机版服务注册中心
      defaultZone: http://eureka-18761:18761/eureka/,http://eureka-18763:18763/eureka/

---
server:
  port: 18763

spring:
  config:
    activate:
      on-profile: eureka-18763

eureka:
  instance:
    #eureka server instance ID
    hostname: eureka-18763
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: true
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      #单机版服务注册中心
      defaultZone: http://eureka-18761:18761/eureka/,http://eureka-18762:18762/eureka/

