server:
  port: 9300
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #路由 id,没有固定规则，但唯一，建议与服务名对应
        - id: eureka-client-producer
          #动态路由，使用服务名代替上面的具体带端口
          uri:  lb://eureka-client-producer
          #以下是断言条件，必选全部符合条件
          predicates:
            - Path=/request/** #断言，路径匹配 注意：Path 中 P 为大写
#            - Method=GET  #只能时 GET 请求时，才能访问


eureka:
  instance:
    #instance ID
    hostname: gateway-server
  client:
    service-url:
      #单机版服务注册中心
      defaultZone: http://eureka-18761:18761/eureka/,http://eureka-18762:18762/eureka/,http://eureka-18763:18763/eureka/

